### ISSUE TITLE
技术小记-CSS结构与布局

### ISSUE THREAD

**Issue by xwchris** [xwchris/blog#19]
## 自适应内部元素
对于一个元素来说，如果不设置高度，那么高度会自动适应其内容的高度。如何让width有这样的行为？

1. 使用`float`可以让width随内容自适应，但这样会改变布局
2. `inline-block`水平的元素具有宽度自适应的行为。但这样也达不到完美的要求，因为要让他居中需要为其父容器设置`text-align: center`。
3. 当实在没有办法时，我们会选择自己计算定死宽度但是这样，响应式就无从谈起了。

### 解决方案
在css3中有一个[新的规范](http://w3.org/TR/css3-sizing)，它为`width`和`height`属性定义了一些新的关键字，其中`min-content`满足我们这个需求，它将元素的宽度设为容器内部最大的不可断行元素的宽度。为了给旧版浏览器提供一个平稳的回退样式，需要提供一个固定的`max-width`值。
```css
div {
	max-width: 300px;
	max-width: min-content;
	margin: auto;
}
```

## 精确控制表格列宽
众所周知，表格的布局很难预测。这是因为列宽根据其内容进行调整，即使我们显示的指定了`width`，也只能起到类似提示的作用。那么如何让表格更加可控那？

### 解决方案
解决方案来自css2.1中的`table-layout`，它的默认值是`auto`，其默认模式被称为”自动表格布局算法”，这也是我们熟悉的表格行为。不过，如果给它传入`fixed`，这个值的行为更加可控，它将较少的控制权留给渲染引擎，更多的控制权给了开发者。我们设置的宽度等等样式会直接起作用，溢出行为（包括text-overflow）与其他元素是一样的。表格的内容将只能影响表格行的高度了。

## 根据兄弟元素的数量来设置样式
该场景应用于当列表元素数量不同时给予不同的样式，我们使用css在不同的数量下命中所有的列表元素那？这是一个难题。

### 解决方案

对于一个特殊场景只有一个元素，我们可以使用`:only-child`伪类选择器来命中该元素，它就是为这种场景设计的
```css
li:only-child {
	/ * 当只有一个列表项时的样式 */
}
```

实际上`:only-child`等效于`:first-child:last-child`即该元素既是第一个也是最后一个元素。

如果我们想命中有四个列表项的所有的列表元素，可以借鉴该方法，配合兄弟选择器使用如下代码。
```css
li:first-child:nth-last-child(4),
li:first-child:nth-last-child(4) ~ li {
	/* 当列表项正好包含四项时，命中所有列表项 */
}
```

如果不是确切的数字，选命中某个范围之后的元素，可以配合`nth-child(n+a)`来实现
```css
li:first-child:nth-last-child(n+4),
li:first-child:nth-last-child(n+4) ~ li {
	/* 当列表至少包含四项时，命中所有列表项 */
}

li:first-child:nth-last-child(-n+4),
li:first-child:nth-last-child(-n+4) ~ li {
	/* 当列表最多包含四项时，命中所有列表项 */
}


li:first-child:nth-last-child(n+2):nth-last-child(-n+6),
li:first-child:nth-last-child(n+2):nth-last-child(-n+6) ~ li {
	/* 当列表包含2~6项时，命中所有列表项 */
}
```

## 垂直居中

垂直居中是及其常见的需求，理论上看似乎十分简单，但在实践中又难以实现的一个效果，可以算是css中广为流传的笑话。

#### 基于绝对定位的解决方案
这第一种方案要求宽高有确定的高度
```css
main {
	position: absolute;
	width: 18em;
	height: 6em;
	top: calc(50% - 3em);
	left: calc(50% -8em);
}

main {
	postion: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	margin: auto;
	width: 18em;
	height: 6em;
}
```

配合`transform`的`translate`属性能够移动元素自身百分比的位置的特定，可以在不指定宽高的情况下实现垂直居中。
```css
main {
	postion: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}
```

#### 基于flexbox的解决方案
这是最佳的解决方案，因为flexbox（伸缩盒）就是专门针对这类需求设置设计的，目前大部分浏览器对flexbox支持的已经相当不错了，但还是不如前面的方案完全。

```css
body {
	display: flex;
	min-height: 100vh;
	margin: 0
}


main: {
	/* 这里只是用margin: auto就能实现也不需要指定宽高 */
	margin: auto;
}
```

## 紧贴底部的页脚
当有如下html页面的结构
```html
<header></header>
<main></main>
<footer></footer>
```

如果`main`中的内容不够`footer`元素会跟随页面向上，这样页面底部有一段空白，用户体验相当不好，我们如何让`footer`在内容不够的时候也保持在底部？

### 固定高度解决方案
根据`header`和`footer`等元素固定高度的部分算出`main`需要的最小高度，这种方案不足的地方在于，没有办法灵活控制，其他部分的高度不能变化
```css
main {
	min-height: calc(100vh - 4em -2em);
	box-sizing: border-box;
}
```

### 更灵活的方案
如果使用flexbox伸缩盒我们的问题可以完美解决，但是存在支持不全的问题，虽然大部分现代浏览器都支持的很好了。
```css
body {
	display: flex;
	flex-flow: column;
	min-height: 100vh;
}

main {
	flex: 1;
}
```
