### ISSUE TITLE
CSS问题及技巧记录

### ISSUE THREAD

**Issue by xwchris** [xwchris/blog#8]
> 本文总结为自己遇到的CSS问题和难点总结整理

## 自适应内部元素
对于一个元素来说，如果不设置高度，那么高度会自动适应其内容的高度。如何让width有这样的行为？

1. 使用`float`可以让width随内容自适应，但这样会改变布局
2. `inline-block`水平的元素具有宽度自适应的行为。但这样也达不到完美的要求，因为要让他居中需要为其父容器设置`text-align: center`。
3. 当实在没有办法时，我们会选择自己计算定死宽度但是这样，响应式就无从谈起了。

### 解决方案
在css3中有一个[新的规范](http://w3.org/TR/css3-sizing)，它为`width`和`height`属性定义了一些新的关键字，其中`min-content`满足我们这个需求，它将元素的宽度设为容器内部最大的不可断行元素的宽度。为了给旧版浏览器提供一个平稳的回退样式，需要提供一个固定的`max-width`值。
```css
div {
	max-width: 300px;
	max-width: min-content;
	margin: auto;
}
```

## 精确控制表格列宽
众所周知，表格的布局很难预测。这是因为列宽根据其内容进行调整，即使我们显示的指定了`width`，也只能起到类似提示的作用。那么如何让表格更加可控那？

### 解决方案
解决方案来自css2.1中的`table-layout`，它的默认值是`auto`，其默认模式被称为”自动表格布局算法”，这也是我们熟悉的表格行为。不过，如果给它传入`fixed`，这个值的行为更加可控，它将较少的控制权留给渲染引擎，更多的控制权给了开发者。我们设置的宽度等等样式会直接起作用，溢出行为（包括text-overflow）与其他元素是一样的。表格的内容将只能影响表格行的高度了。

## 根据兄弟元素的数量来设置样式
该场景应用于当列表元素数量不同时给予不同的样式，我们使用css在不同的数量下命中所有的列表元素那？这是一个难题。

### 解决方案

对于一个特殊场景只有一个元素，我们可以使用`:only-child`伪类选择器来命中该元素，它就是为这种场景设计的
```css
li:only-child {
	/ * 当只有一个列表项时的样式 */
}
```

实际上`:only-child`等效于`:first-child:last-child`即该元素既是第一个也是最后一个元素。

如果我们想命中有四个列表项的所有的列表元素，可以借鉴该方法，配合兄弟选择器使用如下代码。
```css
li:first-child:nth-last-child(4),
li:first-child:nth-last-child(4) ~ li {
	/* 当列表项正好包含四项时，命中所有列表项 */
}
```

如果不是确切的数字，选命中某个范围之后的元素，可以配合`nth-child(n+a)`来实现
```css
li:first-child:nth-last-child(n+4),
li:first-child:nth-last-child(n+4) ~ li {
	/* 当列表至少包含四项时，命中所有列表项 */
}

li:first-child:nth-last-child(-n+4),
li:first-child:nth-last-child(-n+4) ~ li {
	/* 当列表最多包含四项时，命中所有列表项 */
}


li:first-child:nth-last-child(n+2):nth-last-child(-n+6),
li:first-child:nth-last-child(n+2):nth-last-child(-n+6) ~ li {
	/* 当列表包含2~6项时，命中所有列表项 */
}
```

## 垂直居中

垂直居中是及其常见的需求，理论上看似乎十分简单，但在实践中又难以实现的一个效果，可以算是css中广为流传的笑话。

#### 基于绝对定位的解决方案
这第一种方案要求宽高有确定的高度
```css
main {
	position: absolute;
	width: 18em;
	height: 6em;
	top: calc(50% - 3em);
	left: calc(50% -8em);
}

main {
	postion: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	margin: auto;
	width: 18em;
	height: 6em;
}
```

配合`transform`的`translate`属性能够移动元素自身百分比的位置的特定，可以在不指定宽高的情况下实现垂直居中。
```css
main {
	postion: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}
```

#### 基于flexbox的解决方案
这是最佳的解决方案，因为flexbox（伸缩盒）就是专门针对这类需求设置设计的，目前大部分浏览器对flexbox支持的已经相当不错了，但还是不如前面的方案完全。

```css
body {
	display: flex;
	min-height: 100vh;
	margin: 0
}


main: {
	/* 这里只是用margin: auto就能实现也不需要指定宽高 */
	margin: auto;
}
```

## 紧贴底部的页脚
当有如下html页面的结构
```html
<header></header>
<main></main>
<footer></footer>
```

如果`main`中的内容不够`footer`元素会跟随页面向上，这样页面底部有一段空白，用户体验相当不好，我们如何让`footer`在内容不够的时候也保持在底部？

### 固定高度解决方案
根据`header`和`footer`等元素固定高度的部分算出`main`需要的最小高度，这种方案不足的地方在于，没有办法灵活控制，其他部分的高度不能变化
```css
main {
	min-height: calc(100vh - 4em -2em);
	box-sizing: border-box;
}
```

### 更灵活的方案
如果使用flexbox伸缩盒我们的问题可以完美解决，但是存在支持不全的问题，虽然大部分现代浏览器都支持的很好了。
```css
body {
	display: flex;
	flex-flow: column;
	min-height: 100vh;
}

main {
	flex: 1;
}
```

## 让高和宽等比例伸缩
在响应式开发中很多情况下需要宽度随容器宽度进行伸缩可以使用百分比%来解决，但是由于高度百分比%是相对于父容器的高度进行比较的。这样的话无法实现高度也随宽度进行伸缩。

但是仍有办法来解决，需要了解的是`margin`和`padding`的百分比都是相对于父容器的宽度来进行的，所以在中情况下可以使用`padding`来将高撑起来，至于其中的内容可以在该容器中使用一个布局为`position: absolute`的子块级元素铺满该元素来完成内容的承载。

## 部分动画闪烁问题
有时候会遇到动画闪烁的问题，这个时候可以使用`backface-visibility: hidden`来解决该问题。该属性定义当该元素不面向屏幕时是否可见。

## CSS中的层叠顺序
在没有`z-index`的情况下，`float`不为none的元素层级高于没有定位的元素（就是`positition: static` 默认），定位的元素高于`float`不为none的元素。同时，后面的标签的层级大于前面的标签层级。

手动设置`z-index`。`z-index`的设置对未定位的元素无效，不论怎么设置都可以默认看为`z-index: 0`。`z-index`只能是正负整数和零，小于零的时候会比未定位元素的background层级更低。子元素的层级无论如何都高于父级元素，`z-index`的设置一般针对同级元素之间。

## 块级格式化上下文(BFC)
BFC定义了一块渲染区域的渲染规则。

### 形成BFC的情况
1. 根元素
2. float的值不为none
3. position为absolute或fixed
4. overflow不为visible
5. display为inline-block、table-cell等

### BFC内部渲染规则
1. 块级元素在垂直方向一个接一个的放置
2. 属于同一BFC区域的两个相邻元素的垂直方向的margin会重叠同时元素会尽量靠左放置（对于从左向右的格式化）
3. BFC区域不会与浮动元素发生重叠
4. BFC是一个独立的区域，它的子元素不会影响外面的元素，反之也如此
5. 计算BFC高度时浮动元素也参与计算

## inline
inline元素不能使用css手动设置宽、高和上下外边距。同时很重要的一点改变它的行高并不会改变它的高度。

## inline-block
inline-block属于line-level元素，在他们水平排列的时候如果他们之间有空行（包括空格，回车，Tab），由于会缩成一个空格，所以在元素之间有一个空格，这经常会造成布局宽度计算出现问题，要去掉空格要把他们写在同一行、使用注释或者设置`font-size: 0`等方法来解决。[查看详细解决方法]((https://css-tricks.com/fighting-the-space-between-inline-block-elements/))

当inline-block中没有文字时，该元素底部会与父容器的baseline对齐，所以会看到底部有一点间隙。当有文字的时候，会将文字的baseline与父容器的baseline对齐。但是当使用`vertical-align: center`属性的时候，又相对的是inline-block元素的中点进行对齐。

## transform与position: fixed
任何transform不为none的元素都会为他的后代创建一个包含块，所以后代position为fixed的元素不会再给予viewport进行定位，而是基于该包含块进行。所以有时候在transform子元素中使用`position: fixed`可能不会达到理想的效果。

## border-radius
border-radius拥有8个可控制的属性，按照顺时针方向分别为上左角，上右角，下右角和下左角，每个角又都有水平和垂直两个方向，故而有8个属性。
百分比设定值的时候，垂直方向会按照高度计算，水平方向会按照宽度计算。写法上先水平方向后垂直方向`border-radius: 20px 20px 20px 20px / 20px 20px 20px 20px`的顺序来书写。

## line-height和vertical-align
每个行内元素都有line-box，text-box和baseline。对于非文字的行内元素来说baseline就是他们的下边界。

baseline基线是所有文字排版的标准线，它通常在中偏下的位置。需要注意的是，基线的位置并不是一定的它会根据实际情况进行变化。当容器中没有上线空间可供元素移动时，那么基线为了达到效果就会进行移动。

text-box又称为content-area，它的大小由字体大小和字体种类决定，不同的字体相同的`font-size`也可能会有不同的高度，这是在字体设计时就决定了的。因此`font-size: 16px`的文字的text-box高度并不是16px，会有一定的留白。

line-box是最外层的边界，可以用来控制文字间距，可以通过设置行高（line-height）来控制line-box的高度。

父容器每行都有相应的line-box，text-box和base-line并且他有一个宽度为0的字符称谓strut，虽然看不到，但是它的影响是存在的。比如当设置的子容器的行高小于父容器行高的时候，通常我们会看不到效果（可能在各浏览器行为不一致，这里以chorme为准），这是因为即使子元素的行高缩小了，但是strut的行高并没有变所以该行仍然像之前表现那样撑起该行，让我们看起来没有效果。因为整行的行高是根据各个行内元素的表现来计算出最终结果的。

### vertical-align
vertical-align默认的对齐方式就是将子元素的baseline与父元素的baseline对齐，sub和super则基线相对于父容器基线略微偏下或略微偏下，数值和百分比也是相对于父容器基线定位，百分比大小计算是根据行高来计算的。middle是将子元素的垂直中心点与父容器的基线加上一半的x-height的位置对齐的。text-top和text-bottom是将行内元素的line-box边界与父元素的text-box上下边界对齐。top和bottom是将行内元素的line-box边界与父元素的line-box上下边界对齐。[更多详情查看这里](http://christopheraue.net/2014/03/05/vertical-align/)。

### 图片文字居中对齐
根据以上vertical-align规则，图片跟文字同时使用`vertical-align: middle`可以使文字和图片居中对齐。

## 脱离文档流
脱离文档流的意思是其他元素当做它不存在。当该元素是浮动元素的话，其他元素的文字还是会环绕在该浮动元素周围。position属性如果是absolute和fixed则连文字也会当做他们不存在。

## text-align和direction
`direction`用来规定文本方向。它有三个值`ltr`规定文本从左向右排列，`rtl`规定文本从右向左排列，`inherit`继承父元素。同时它是可继承的。

`text-align`用来规定inline元素的对齐方式，对块级元素无效。`left`和`right`跟左右对齐，`center`中间对齐，`start`和`end`会根据`direction`属性来转化为`left`和`end`。`justify`左右两端都撑满最后一行除外，`justify-all`跟`justify`类似但它包括最后一行。`match-parent`跟`inherit`类似。

### 图片垂直水平居中
图片是内联元素，所以水平居中使用`text-align: center`很容易实现。垂直居中方面在不用绝对定位的前提下，可以利用`vertical-align`属性，使用使用一个辅助内联元素来让图片居中对齐，原理参考上面提到的图片文字居中对齐。这里一共提供三个方法。[查看实际效果](https://jsfiddle.net/xwchris/q3ubt3z0/4/)
1. 使用一个辅助`inline-block`元素，它的高度为100%即跟父容器同高，这样它使用`vertical-align: middle`的时候，就可以让其中点跟父容器基线对齐。这时再img中使用`vertical-align: middle`就可以使img中点跟父容器对齐，从而垂直居中。这里可以看出辅助元素的作用就是改变父容器基线的位置。在水平居中的时候可以使用`text-align: center`但使用这个方法的时候会发现一点小问题。我们会发现图片并没有水平居中，其实如果让辅助元素显示出来比如设置`width: 1px; background-color: red`就会发现该元素和img元素之间有一个小空隙，这个问题在上面inline-block部分有提到过，这里直接在父容器中设置`font-size: 0`就可以解决这个问题了。
2. 通过设置父元素为`display: table-cell`来让父容器表现为表格单元同时设置`vertical-align: middle; text-align: center`。这时图片很类似被一个元素包裹起来并垂直水平居中。检查元素会发现在图片的下面有一个小的空隙，这也是由于基线问题导致的，所以直接在img中使用`vertical-align: middle`就可以解决这个问题，使图片完全居中。
3. 最后一种方法对图片使用绝对定位，设置top, right, bottom, left都为0并设置`margin: auto`就可以使图片垂直居中。或者设置`top: 50%; left: 50%; transform: transition(-50%, -50%)`来使图片居中，这种方法也通用块级元素居中。

## 多行文字垂直居中
单行文字居中很简单，只要设置文字行高和父容器高一样就可以了。多行文字居中，可以利用`display: table;`和`display: table-cell`。设置父容器为`display: table`文字如用span标签来包裹设置为`display: table-cell; vertical-align: middle;`就可实现多行文字处置居中显示。[查看实际效果](https://jsfiddle.net/xwchris/ykwdr61e/)

## 减少代码重复
灵活的css通常更容易扩展，在写出基础样式后，只要用极少的代码就可以扩展出不同的变体，因为只要覆盖一些变量就可以了。

下面的效果实现一个带阴影的按钮效果
```css
padding: 6px 16px;
border: 1px solid #446d88;
background: #58a linear-gradient(#77a0bb, #58a);
border-radius: 4px;
box-shadow: 0 1px 5px gray;
color: white;
text-shadow: 0 -1px 1px #335166;
font-size: 20px;
line-height: 30px;
```

该代码存在一些维护性问题，我们来一一修复。

首先是与字体相关的部分了，如果要改变字号，那我们要同时改变行高，为了更好的维护，我们可以使用倍数行高来表示。同时字号也使用百分比来表示。

```css
font-size: 125%; /* 假设父容器字号为16px */
line-height: 1.5;
```

现在改变父容器的字体大小，按钮也会随之变化，但是其他尺寸会显得很不协调，为了让他们也自动变化，我们使用`em`来改变他们。
```css
padding: .2em .8em;
border-radius: .2em;
box-shadow: 0 .05em .25em gray;
text-shadow: 0 0.05em .05em #335166;
```

现在尺寸方面的问题解决了，但是如果要做一个红色的取消按钮，要改变覆盖四处声明，这不是我们想要的。还有一个难题，要根据按钮的亮面和暗面相对于主色调`#58a`变亮和变暗的程度来分别推导出其他颜色各自的亮色和暗色版本。此外，如果想将按钮放在一个其他背景之上，使用灰色投影显的不协调。

其实只要把半透明的黑色或白色叠加在主色调上，就可以产生主色调的暗色变体和亮色变体，这样就能简单化解这个难题。
```css
border: 1px solid rgba(0,0,0,.1);
background: #58a linear-gradient(hsla(0, 0%, 100%, .2), transparent);
box-shadow: 0 .05em .25em rgba(0,0,0,.5);
text-shadow: 0 -.05em .05em rgba(0,0,0,.5);
```

现在只要覆盖`background-color`属性就能得到不同颜色版本的按钮了。
```css
button.cancel {
	background-color: #c00;
}

button.ok {
	background-color: #6b0;
}
```
